version: '3.5'

networks:
  default:

services:
  messaging:
    command: ["-m", "8222", "-D", "-V"]
    image: nats-streaming
    networks:
      default:
    ports:
    - "4222:4222"
    - "8222:8222"
    - "6222:6222"
